/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Badge } from "./Badge";
import { BadgeCountArgs } from "./BadgeCountArgs";
import { BadgeFindManyArgs } from "./BadgeFindManyArgs";
import { BadgeFindUniqueArgs } from "./BadgeFindUniqueArgs";
import { DeleteBadgeArgs } from "./DeleteBadgeArgs";
import { BadgeService } from "../badge.service";
@graphql.Resolver(() => Badge)
export class BadgeResolverBase {
  constructor(protected readonly service: BadgeService) {}

  async _badgesMeta(
    @graphql.Args() args: BadgeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Badge])
  async badges(@graphql.Args() args: BadgeFindManyArgs): Promise<Badge[]> {
    return this.service.badges(args);
  }

  @graphql.Query(() => Badge, { nullable: true })
  async badge(
    @graphql.Args() args: BadgeFindUniqueArgs
  ): Promise<Badge | null> {
    const result = await this.service.badge(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Badge)
  async deleteBadge(
    @graphql.Args() args: DeleteBadgeArgs
  ): Promise<Badge | null> {
    try {
      return await this.service.deleteBadge(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
