/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Venue } from "./Venue";
import { VenueCountArgs } from "./VenueCountArgs";
import { VenueFindManyArgs } from "./VenueFindManyArgs";
import { VenueFindUniqueArgs } from "./VenueFindUniqueArgs";
import { DeleteVenueArgs } from "./DeleteVenueArgs";
import { VenueService } from "../venue.service";
@graphql.Resolver(() => Venue)
export class VenueResolverBase {
  constructor(protected readonly service: VenueService) {}

  async _venuesMeta(
    @graphql.Args() args: VenueCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Venue])
  async venues(@graphql.Args() args: VenueFindManyArgs): Promise<Venue[]> {
    return this.service.venues(args);
  }

  @graphql.Query(() => Venue, { nullable: true })
  async venue(
    @graphql.Args() args: VenueFindUniqueArgs
  ): Promise<Venue | null> {
    const result = await this.service.venue(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Venue)
  async deleteVenue(
    @graphql.Args() args: DeleteVenueArgs
  ): Promise<Venue | null> {
    try {
      return await this.service.deleteVenue(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
